name: Deploy to AWS EC2 instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [16.17.1]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/my-app/
          remote_host: ec2-13-55-228-15.ap-southeast-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'
